package com.impostor.app.ui.screens

import app.cash.paparazzi.DeviceConfig
import app.cash.paparazzi.Paparazzi
import com.android.ide.common.rendering.api.SessionParams
import org.junit.Rule
import org.junit.Test

/**
 * Generated by the Compose Preview extension (Compose: Generate Previewer Test).
 *
 * Reads COMPOSE_PREVIEW_FILTER=FunctionName1,FunctionName2 and renders only the
 * matching previews; renders everything when the env var is absent.
 *
 * Safe to edit — regenerating overwrites this file after confirmation.
 */
class ComposePreviewer {

    @get:Rule
    val paparazzi = Paparazzi(
        deviceConfig = DeviceConfig.PIXEL_5,
        renderingMode = SessionParams.RenderingMode.SHRINK,
        theme = "android:Theme.Material.Light.NoActionBar",
    )

    @Test
    fun snapshots() {
        val filter = System.getenv("COMPOSE_PREVIEW_FILTER")
            ?.split(",")
            ?.map { it.trim() }
            ?.filter { it.isNotEmpty() }

        fun shouldRender(name: String) = filter == null || name in filter

        if (shouldRender("SplashPreview")) {
            paparazzi.snapshot(name = "SplashPreview") { SplashPreview() }
        }
        if (shouldRender("OnboardingPreview")) {
            paparazzi.snapshot(name = "OnboardingPreview") { OnboardingPreview() }
        }
        if (shouldRender("HomePreview")) {
            paparazzi.snapshot(name = "HomePreview") { HomePreview() }
        }
        if (shouldRender("PlayerCountPreview")) {
            paparazzi.snapshot(name = "PlayerCountPreview") { PlayerCountPreview() }
        }
        if (shouldRender("PlayerNamePreview")) {
            paparazzi.snapshot(name = "PlayerNamePreview") { PlayerNamePreview() }
        }
        if (shouldRender("ClassicImpostorCountPreview")) {
            paparazzi.snapshot(name = "ClassicImpostorCountPreview") { ClassicImpostorCountPreview() }
        }
        if (shouldRender("PlayerTurnPreview")) {
            paparazzi.snapshot(name = "PlayerTurnPreview") { PlayerTurnPreview() }
        }
        if (shouldRender("WordRevealPreview")) {
            paparazzi.snapshot(name = "WordRevealPreview") { WordRevealPreview() }
        }
        if (shouldRender("QuestionRevealPreview")) {
            paparazzi.snapshot(name = "QuestionRevealPreview") { QuestionRevealPreview() }
        }
        if (shouldRender("MrWhiteRevealPreview")) {
            paparazzi.snapshot(name = "MrWhiteRevealPreview") { MrWhiteRevealPreview() }
        }
    }
}
